# Generated by Django 5.2.6 on 2025-09-23 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Title'),
                ),
                (
                    'occasion',
                    models.CharField(
                        choices=[
                            ('birthday', 'Birthday'),
                            ('wedding', 'Wedding'),
                            ('charity', 'Charity'),
                            ('medical', 'Medical'),
                            ('education', 'Education'),
                            ('travel', 'Travel'),
                            ('business', 'Business'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=25,
                        verbose_name='Occasion',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'planned_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Leave it empty for endless collection.',
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Amount planned',
                    ),
                ),
                (
                    'current_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Amount current',
                    ),
                ),
                (
                    'donations_count',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Number of donations'
                    ),
                ),
                (
                    'cover_image',
                    models.ImageField(
                        blank=True,
                        upload_to='colletcs/covers/',
                        verbose_name='Cover',
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='End date'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Active'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Updated'),
                ),
            ],
            options={
                'verbose_name': 'collect',
                'verbose_name_plural': 'Collects',
                'ordering': ('-created_at',),
            },
        ),
    ]
