# Generated by Django 5.2.6 on 2025-09-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddConstraint(
            model_name='collect',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_collect_per_author'),
        ),
        migrations.AddConstraint(
            model_name='collect',
            constraint=models.CheckConstraint(condition=models.Q(('occasion__in', ['b', 'w', 'c', 'm', 'e', 't', 'b', 'o'])), name='collects_collect_occasion_valid'),
        ),
    ]
