# Generated by Django 5.2.6 on 2025-09-24 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collect',
            name='collects_collect_occasion_valid',
        ),
        migrations.AddConstraint(
            model_name='collect',
            constraint=models.CheckConstraint(condition=models.Q(('occasion__in', ['birthday', 'wedding', 'charity', 'medical', 'education', 'travel', 'business', 'other'])), name='collects_collect_occasion_valid'),
        ),
    ]
